name: polymathic
description: Your life, re-organized.

publish_to: 'none'

version: 0.0.3+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fast_i18n: ^1.6.0
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.8
  flutter_icons: ^1.1.0
  flutter_svg: ^0.18.0
  dotted_border: ^1.0.6
  charts_flutter: ^0.9.0
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_android: "assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/icon-710x599-ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#3F51B5"
  adaptive_icon_foreground: "assets/images/foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/svg/