name: polymathic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.8
  flutter_icons: ^1.1.0
  flutter_svg: ^0.17.4
  dotted_border: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svg/